### ISSUE TITLE
[Feature Request] Function files that are run when different 

### ISSUE THREAD

**Issue by pixelpax** [graphile/migrate#35]
## Problem
More than half of the content in my migrations so far is adding or modifying functions.

Every time I make a change to to one of these functions, I have to copy it into my `current.sql` file to change one line. A major downside here is that I can't see a clean git history of the function.

## Possible Solution
The simplest solution I can think of would be to store a function file (or several) which run after current.sql runs (while `watch` is running) and is appended to the end of each migration upon `commit`. Unlike `current.sql`, `functions.sql` contains only `create or replace function` statements, and is not cleared on commit.

## Potential Problems
- Order of execution of the declaration matters. We would probably want to store the current state of functions.sql in every commit. Functions would either have to be in one file or concatenated into the same file in a predictable order.
- Deleting/renaming functions would probably have to still happen in 
- Extra time on migrate (but probably not much because declaration is a constant operation
- Extra declarations at the bottom of migration files (but these are immutable archives, so we may not care).
- We would probably want to copy the previous migration's state of `functions.sql` on `uncommit`.

## Also
I'm super new at this. Sorry in advanced if this is a non-problem, solved problem, unsolvable problem or just low priority/low value! Just opening up the discussion.

**Comment by benjie** [comment]
This sounds like it would be a perfect fit for the `afterCurrent` hook? Apparently I forgot to document this, so I've added docs here: https://github.com/graphile/migrate/commit/b5befc984812346120cd3ea85246f50841276cc5#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by myknbani** [comment]
Thank you @benjie for the awesome work on Postgraphile and graphile-migrate! 🔥🔥

> Every time I make a change to to one of these functions, I have to copy it into my current.sql file to change one line. A major downside here is that I can't see a clean git history of the function.

I also prefer in-place editing of functions, instead of copying the entire function code.  Here's my workaround:

I created a `functions/` directory and used the `afterCurrent` hook.  One observation is that files outside of `migrations/current/` or the `current.sql` file are not watched.  So to trigger graphile-migrate to run the edited function in `migrations/functions/some-func.sql` in watch mode, I had to do something like:

```bash
echo "SELECT $RANDOM;" > migrations/current/999-hack.sql
```

It needs to be a random number so that graphile-migrate considers it as a change.  It's so smart that it's immune to comments and whitespace-only changes 😂.  Aside from migration files containing the harmless SELECT statements, it seems to work.

```sql
--! Message: fix bug in function

--! split: 1-current.sql
-- Enter migration here

--! split: 999-hack.sql
SELECT 28142;
```

It seems to be a necessity since we can't `graphile-migrate commit` empty migrations, nor trigger the hooks without a new `committed/00000#-some-message.sql` file.
