### ISSUE TITLE
Allow current.sql to be split into several files

### ISSUE THREAD

**Issue by lukaspili** [graphile/migrate#40]
Hello,

After working for more than 1 month with graphile migrate, I would like to be able to split a big `current.sql` into several files smaller files. In practice, it's actually more useful than named commits as I initially requested in #28.

During the initial development phase of a project, we don't want to commit/track migrations. Our schema changes a lot, so we don't want to start building a messy migration history. We'd rather share a big `current.sql` between the development team, and commit a clean initial migration when our schema is stable. 
Also during that time, we don't release anything on a production/public environment. We'd rather enjoy the flexibility of being able to reset the database (+run the seeds) every time `current.sql` changes.

It works great so far, except for the fact that `current.sql` grew to more than 2k lines, which is not great for readability. It would be useful to be able to split `current` into smaller files. For instance `custom_1_utils.sql`, `current_2_create_user.sql`, `current_3_mutations.sql`, etc.

This feature is much needed for us so I plan to work on it. If you feel it's too specific or beyond the scope of migrate I will just make a fork. But if you're interested in a PR, here's how I see the specs:

* Automatically detect between a single or multiple `current` files, do not allow both;
* Not breaking, optional addition;
* Filename for split current is `current_[int]_[description].sql`;
* `[int]` defines the order in which the sql files are run (doesn't have to be sequential, but must be >= 1 and unique)
* `[description]` is just a text without any implication;
*  On commit, it merges all `current_` files into a single sql commit. The commit file is formated in such way that it's possible to re-create all `current_` files on `uncommit`.

I didn't think too much about the format of the commit. It definitely needs to be specific enough so it doesn't clash with a user's own comments. For instance:

```sql
--! Previous:
--! Hash:
--! Merged:
--!   1: utils
--!   2: users
 
--! Part: 1 - utils
...

--! Part: 2 - users
...
```

Let me know what you think. Thanks!

**Comment by benjie** [comment]
Would MIME-style separators make sense?

**Comment by lukaspili** [comment]
Do you mean something like this: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html?

**Comment by benjie** [comment]
Specifically the `boundary=gc0p4Jq0M2Yt08jU534c0p` and `--gc0p4Jq0M2Yt08jU534c0p` parts, yeah. Just a thought (rather than re-inventing the wheel). We could also use MIME-style headers (inside SQL `--` comments) to indicate things like filename, etc.

TBH using a custom syntax for this is fine, I just wanted to evaluate what using an existing solution might look like.

**Comment by lukaspili** [comment]
Sure. It would be interesting to use the MIME format if we use it for more than just boundary splitting. It should even be possible to use an existing MIME parser/decoder. But I think that for splitting only I think it's overkill. 
But I don't really have strong opinions on the subject. I'm happy to implement the format you think it's best.

**Comment by lukaspili** [comment]
I'm also wondering what would be best between having several `current_` files VS a `current` forlder:

```
migrations/
  commited/
  current-1-foo.sql
  current-2-bar.sql
```

```
migrations/
  commited/
  current/
    1-foo.sql
    2-bar.sql
```

Any preference?

**Comment by benjie** [comment]
`current/` folder, split on `--! split`, just numbers, names optional.

**Comment by benjie** [comment]
Hey sorry for the short comment; figured better to give opinion fast rather than wait for a full response a few days later :)

I like this idea, it could certainly make things more manageable for those large initial migrations. We might be able to further optimise this by *only* running the file that actually changed in watch mode rather than the entire migration, though this requires each file to be idempotent in its own right, so it's not clear if this is the right thing to do or not. It's be great for avoiding things like data resetting when you're just replacing a function though :) I think there will likely be some issues with this though.

Another thing is splitting a file in two; say you have `1-foo`, `2-barbaz` and `3-qux` and you want to split file `2-barbaz` into two files could we do so by adding a `--! split` comment to `2` and having graphile-migrate do the split for us, or would it require the `graphile-migrate commit && graphile-migrate uncommit` flow for that to happen?

I'm thinking we could use something like a JSON5 payload (sans braces) `--! split name: "current_user_id"` to add the optional name.

I'm also thinking that the entire project would work in this way by detecting if there's either a `current/` folder or a `current.sql` file and sticking to the convention.

The first file would have no `--! split` comment, but it would need to be able to have a name - but potentially we want a name for the whole migration anyway so maybe `--! meta name: "..."` would work.

One issue that sticks out to me is `--! no-transaction` because it technically applies to the whole migration but if we split the migration then it's not clear what a `--! no-transaction` comment in the 3rd file would mean. It's also means that whether a file is in a transaction or not would be affected by the migrations before it. It's not clear to me how to solve this yet, perhaps we require that all files agree on this header (they all must have it, or they all must omit it) and generally you're encouraged to use no-transaction for the smallest (single file) migration you can.

**Comment by lukaspili** [comment]
No problem, appreciate the fast responsiveness :)

Good idea for re-running only modified files. I will try to implement this behaviour.

About adding `--! split` into an existing file in order for it to be splitted: is there really a gain over creating a new file manually + cut paste? Feels like adding a lot of complexity to `graphile commit` for something that can be done naturally in another way.

Regarding `--! no-transaction` I have yet to encounter a case where I have to use it in a migration, so I don't really have strong opinions on the matter. I would say that in order to keep the initial PR small enough, we can start by enforcing all files having the same definition regarding `--! no-transaction`. 
It would also be consistent with the current behaviour for migrations files (once it's merged and commited).

I should be able to send the PR by the end of the week.

**Comment by benjie** [comment]
> About adding --! split into an existing file in order for it to be splitted: is there really a gain over creating a new file manually + cut paste? Feels like adding a lot of complexity to graphile commit for something that can be naturally done in another way.

Mostly just that if you've got 4 files and you split file number 2, you'd have to rename files 3 and 4. But I think `commit && uncommit` will solve this for you so no need to explicitly handle it.

> Regarding `--! no-transaction` I have yet to encounter a case where I have to use it in a migration, so I don't really have strong opinions on the matter. 

I explicitly avoid having to use it, which is why the feature is under-developed.

> I would say that in order to keep the initial PR small enough, we can start by enforcing all files having the same definition regarding `--! no-transaction`.

:+1: This seems a sensible approach.

> I should be able to send the PR by the end of the week.

No rush; I'm still way behind catching up from the holidays!

**Comment by charlex** [comment]
fwiw, I wrote a small script for this:

```ts
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve, join } from 'path';

import { textSync } from 'figlet';

const run = () => {
  const GENERATED_FILE_NAME = 'current.generated.sql';

  const PATH_TO_MIGRATIONS_DIR = resolve(
    join(__dirname, '../../..', 'migrations')
  );

  const GENERATED_FILE_PATH = resolve(
    join(PATH_TO_MIGRATIONS_DIR, GENERATED_FILE_NAME)
  );

  const PATH_TO_CURRENT_DIR = resolve(join(PATH_TO_MIGRATIONS_DIR, 'current'));

  const COMMENT_DIVIDER_LENGTH = 60;

  const COMMENT_DIVIDER = `${Array.from({ length: COMMENT_DIVIDER_LENGTH })
    .map(() => '-')
    .join('')}\n`;

  const replaceNewLines = (str: string) => {
    return str.replace(/\n/gm, `\n${pfix}`).replace(/^\s/, `${pfix}`);
  };

  const pfix = '----    ';

  const toCommentHeader = (content: string) => {
    return `${COMMENT_DIVIDER}${COMMENT_DIVIDER}${replaceNewLines(
      content
    )}\n${COMMENT_DIVIDER}${COMMENT_DIVIDER}\n\n`;
  };

  const readdirSyncWithPath = (path: string) => {
    return readdirSync(path).map((n) => join(path, n));
  };

  const pathToFileName = (path: string) => {
    return path.replace(PATH_TO_CURRENT_DIR, '').replace(/^\//, '');
  };

  const getFileNumberFromPath = (path: string) => {
    const fname = pathToFileName(path);
    const idx = fname.split('-');
    if (typeof idx[0] !== 'string') {
      throw new Error(
        'Filename does not start with a string/number followed by a hyphen'
      );
    }
    try {
      return parseInt(idx[0], 10);
    } catch (e) {
      throw new Error(
        'Filename does not start with a string/number followed by a hyphen'
      );
    }
  };

  const mergeFilesWithPath = (path: string) => {
    return readdirSyncWithPath(path)
      .sort((a, b) => {
        return getFileNumberFromPath(a) - getFileNumberFromPath(b);
      })
      .reduce((acc, fpath, idx) => {
        const body = readFileSync(fpath).toString('utf-8');
        const fname = fpath.replace(PATH_TO_CURRENT_DIR, '').replace(/^\//, '');
        const header = toCommentHeader(`---- File #${idx + 1}: ${fname}`);
        return `${acc}${header}${body}\n\n`;
      }, '');
  };

  const GENERATED_HEADER = toCommentHeader(
    `${textSync(`Current.sql`, {
      font: 'Soft',
    })}`
  );

  //;
  const MERGED_CURRENT_BODY = mergeFilesWithPath(PATH_TO_CURRENT_DIR);
  const GENERATED_BODY = `${GENERATED_HEADER}\n\n${MERGED_CURRENT_BODY}`;

  // eslint-disable-next-line no-console
  console.log(
    'Writing to',
    GENERATED_FILE_PATH,
    'With:',
    `\n\n${GENERATED_BODY}`
  );

  writeFileSync(GENERATED_FILE_PATH, GENERATED_BODY);
};

run();
```
